@startuml
'https://plantuml.com/sequence-diagram
'sequenceDiagram
title Администратор наблюдает за ходом голосования
    Admin->>Frontend: Открывает панель администратора
    Frontend->>API: GET /polls/mine
    API->>DB: SELECT * FROM Poll WHERE created_by = ?
    DB-->>API: Список голосований

    Frontend->>WS: Подписаться на updates:{poll_id}
    WS-->>Frontend: При получении обновлений — отображать в реальном времени

@enduml