@startuml
'https://plantuml.com/use-case-diagram

'---
title: Use Case Diagram — Система анонимного голосования
'---
'classDiagram
    actor User
    actor Admin
    actor System

    User --> (Голосовать)
    User --> (Просматривать активные голосования)
    User --> (Видеть результаты)

    Admin --> (Создать голосование)
    Admin --> (Настроить параметры голосования)
    Admin --> (Запустить/остановить голосование)
    Admin --> (Просматривать результаты в реальном времени)
    Admin --> (Просматривать аудит-логи)

    System -up-> (Проверить право голоса)
    System -up-> (Заблокировать повторное голосование)
    System -up-> (Обновить результаты в реальном времени)
    System -up-> (Залогировать голос)

    (Голосовать) ...> (Проверить право голоса) : <<include>>
    (Голосовать) ...> (Заблокировать повторное голосование) : <<include>>
    (Голосовать) ...> (Залогировать голос) : <<include>>
    (Голосовать) ...> (Обновить результаты в реальном времени) : <<include>>

    (Создать голосование) .> (Настроить параметры голосования) : <<include>>

    note right of (Голосовать)
      Анонимное голосование.
      Проверка по email или JWT.
      Поддержка одного или нескольких выборов.
    end note

    note right of (Обновить результаты в реальном времени)
      Задержка ≤ 4 сек.
      Через WebSocket / SSE.
    end note

    note left of (Залогировать голос)
      Сохраняется: IP, User-Agent,
      метод аутентификации, время.
      Только для аудита.
    end note

    note left of Admin
      Может создавать и управлять
      голосованиями, просматривать
      результаты и логи.
    end note

    note right of User
      Пользователь не аутентифицируется
      напрямую. Право голоса проверяется
      по токену (JWT/email).
    end note
@enduml

@startuml


actor User
rectangle "Просмотр сайта" {
  (Голосовать) as UC1
  (Просматривать активные голосования) as UC2
  (Видеть результаты) as UC3
}
User -right-> UC1
User -right-> UC2
User -right-> UC3

left to right direction
actor Admin as fc2

rectangle "Администрирование сайта" {
  usecase "Создать голосование" as AUC1
  usecase "Настроить параметры голосования" as AUC2
  usecase "Запустить/остановить голосование" as AUC3
  usecase "Просматривать результаты в реальном времени" as AUC4
  usecase "Просматривать аудит-логи" as AUC5
}
fc2 -right-> AUC1
fc2 -right-> AUC2
fc2 -right-> AUC3
fc2 -right-> AUC4
fc2 -right-> AUC5

left to right direction
actor System as fc3
rectangle "Система сайта" {
  usecase "Проверить право голоса" as SUC1
  usecase "Заблокировать повторное голосование" as SUC2
  usecase "Обновить результаты в реальном времени" as SUC3
  usecase "Залогировать голос" as SUC4
}

fc3 -right-> SUC1
fc3 -right-> SUC2
fc3 -right-> SUC3
fc3 -right-> SUC4

UC1 .> SUC1 : <<include>>
UC1 .> SUC2 : <<include>>
UC1 .> SUC3 : <<include>>
UC1 .> SUC4 : <<include>>

AUC1 .> AUC2 : <<include>>


@enduml


@startuml
' отдельно User

'---
title: Use Case Diagram — Система анонимного голосования
'---
'classDiagram
    actor User

    User --> (Голосовать)
    User --> (Просматривать активные голосования)
    User --> (Видеть результаты)

    note right of (Голосовать)
      Анонимное голосование.
      Проверка по email или JWT.
      Поддержка одного или нескольких выборов.
    end note

    note right of User
      Пользователь не аутентифицируется
      напрямую. Право голоса проверяется
      по токену (JWT/email).
    end note
@enduml

@startuml
'https://plantuml.com/use-case-diagram

'---
title: Use Case Diagram — Система анонимного голосования
'---
' отдельно для администратора
    actor Admin

    Admin --> (Создать голосование)
    Admin --> (Настроить параметры голосования)
    Admin --> (Запустить/остановить голосование)
    Admin --> (Просматривать результаты в реальном времени)
    Admin --> (Просматривать аудит-логи)

    (Создать голосование) .> (Настроить параметры голосования) : <<include>>

    note left of Admin
      Может создавать и управлять
      голосованиями, просматривать
      результаты и логи.
    end note

@enduml

