openapi: 3.0.0
info:
  title: Voting API
  version: 1.0.0
  description: API для голосования в опросах

paths:
  /api/vote:
    post:
      summary: Проголосовать в опросе
      description: Позволяет пользователю отправить свой голос по одному или нескольким вопросам опроса
      operationId: submitVote
      tags:
        - Voting
      requestBody:
        description: Данные голосования
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteRequest'
      responses:
        '201':
          description: Голос успешно принят
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoteResponse'
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Опрос или вопрос не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Пользователь уже голосовал
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    VoteRequest:
      type: object
      required:
        - pollId
        - userId
        - answers
      properties:
        pollId:
          type: integer
          example: 1
          description: Идентификатор опроса
        userId:
          type: string
          example: "user_12345"
          description: Уникальный идентификатор пользователя (или сессии)
        answers:
          type: array
          description: Список ответов на вопросы
          items:
            type: object
            required:
              - questionId
              - answer
            properties:
              questionId:
                type: integer
                example: 101
                description: Идентификатор вопроса
              answer:
                oneOf:
                  - type: integer
                    example: 2
                    description: Выбранный номер варианта (для single/multiple)
                  - type: array
                    items:
                      type: integer
                    example: [1, 3]
                    description: Список выбранных вариантов (для multiple choice)
                  - type: string
                    example: "Мой любимый язык — Python"
                    description: Текстовый ответ
      example:
        pollId: 1
        userId: "user_abc123"
        answers:
          - questionId: 101
            answer: 2
          - questionId: 102
            answer: [1, 3]
          - questionId: 103
            answer: "Отличный опрос!"

    VoteResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: "Ваш голос успешно учтён"
        voteId:
          type: string
          example: "vote_98765"
          description: Уникальный идентификатор голоса
        submittedAt:
          type: string
          format: date-time
          example: "2023-10-05T12:34:56Z"

    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Bad Request"
        details:
          type: string
          example: "Поле 'answer' обязательно для вопроса 101"